### ISSUE TITLE
Design issues to fix with the new design

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/assistant#100]
### Which version of assistant are you using?

2.0.1

### Which version of Nextcloud are you using?

30.0.0 dev (daily instance)

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Describe the Bug

There are some things to adjust following the design adjustments from https://github.com/nextcloud/server/issues/45751 and https://github.com/nextcloud/server/issues/45657

In Assistant, they seem to be only a few, namely:

- [ ] The input fields are too tall and use the thick border – seems to still use the old input field component?
- [x] The "New conversation" button seems custom, should be a tertiary button component so the border and radius is consistent
- [x] The header seems to be too tall, possibly manually set height. Notice that the text with the date is lower than the left navigation toggle

![image](https://github.com/nextcloud/assistant/assets/925062/c8453308-8e1c-4993-92b6-9dc0154543d1)

### Expected Behavior

Design to be adjusted :D

### To Reproduce

Open the Assistant on the daily instance.

**Comment by julien-nc** [comment]
> The input fields are too tall and use the thick border

This is [NcRichContenteditable](https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable) which still has a thick border in nc/vue 8.14.0.

Shall we wait for a nc/vue update or dirty-patch this in the assistant right now?
