### ISSUE TITLE
Nextcloud assistant (can) leak user data to third party providers

### ISSUE THREAD

**Issue by ThibautPlg** [nextcloud/assistant#104]
### Which version of assistant are you using?

1.1.0

### Which version of Nextcloud are you using?

28.0.5

### Describe the Bug

Hi,
Nextcloud is invested in providing the best tools to use AI providers as informed as possible (I'm thinking of the Ethical rating and other public statements)

However I was very surprised to find in the pre-made prompts regarding "Chat with AI" that Nextcloud is always sending the User Display name to the third party service. This is present in at least two places:
- Chat User Instructions for Chat Completions 
- Chat User Instructions for Title Generation 

When using Nextcloud in a company, chances are that the user display name is a person full name or a company email. In both cases, Nextcloud is sending OpenAI (or whoever) what I consider to be personal data.

Best regards,

### Expected Behavior

This should be a toggle-able setting, allowing to send anonymized prompts to a service. 
If not, it **should be very clear for the administrator that the service will send to third parties the full display name of it users**. Maybe through a notification, a warning or whatever.

If I noticed this part of the configuration earlier (**which I don't because this came with later updates**), I would have changed the "instructions" snippets. 

### To Reproduce

Install the app

**Comment by julien-nc** [comment]
Thanks for reporting this. Isn't it enough to be able to change the chat and title generation prompts?

You can keep the default one and replace `{user}` by `a Nextcloud user` (and even use your Nextcloud instance name instead of `Nextcloud`).

**Comment by ThibautPlg** [comment]
From a technical point of view I agree, the solution is right here. I was expecting a discussion rather than a configuration workaround. 
- Why is the default behavior leaking the username? and/or couldn't it be the opposite? 
- How to communicate better on this and inform an administrator that after installing the app it has to **not forget** to go update the prompts. 

**I feel stuck in a opt-out situation where I'm not even informed of this behavior.** 

Right now we're testing the assistant through Nextcloud instances and when my coworkers discovered this, some negative reactions raised.
- Trust issue against the software: why is Nextcloud sharing my personal data? Aren't they pro "ethical AI"?
- Trust issue against the admin team: why did they let Nextcloud share my personal data (my bad here, but as I said earlier, these prompts were not here on the initial install)

Last detail that is not as important for us, but can be one "at scale": every assistant (initial) chat is by default consuming 78 tokens for Chat Completions and 43 for Title Generation.

**Comment by julien-nc** [comment]
The default instruct prompts do not include the display name anymore.
This will come in the next Assistant release.
