### ISSUE TITLE
Rescheduling Tasks from the context menu in the previous task list does not send the type parameter in the POST request

### ISSUE THREAD

**Issue by dhx** [nextcloud/assistant#140]
### Which version of assistant are you using?

2.1.0

### Which version of context_chat are you using?

3.1.0

### Which version of Nextcloud are you using?

v30.0.0

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

### Describe the Bug

When trying to reschedule any (testet with "Translate", "Context Chat" and "Generate Text") Task directly from the "Try Again" context action (clicking on the three dots) an Error shows up without delay:

Error Log -> Argument `#2` ($type) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 208 in file '/var/www/nextcloud/core/Controller/TaskProcessingApiController.php' line 122
Access Log -> "POST /ocs/v2.php/taskprocessing/schedule HTTP/1.1" 500
UI -> Assistant error: failure 500 Internal Server Error

Opening the task first in the task log and starting it from there works and includes the type parameter in the POST body.

### Expected Behavior

The task should be rescheduled.

### To Reproduce

1. Start a Context Chat Task
2. Open the 'Previous "Context Chat" tasks'
3. In the list, click on the three dots and on "Try again"
4. Error

**Comment by kyteinsky** [comment]
Would you mind mentioning the version of the assistant app you're using? It can be found in the Apps page or with this command:
```
occ app:list | grep assistant
```

**Comment by dhx** [comment]
@kyteinsky sure:
```
assistant: 2.1.0
```
