### ISSUE TITLE
Centered modal close icon

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/assistant#159]
### Which version of assistant are you using?

The one for 30.0.2

### Which version of Nextcloud are you using?

30.0.2

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Describe the Bug

![Image](https://github.com/user-attachments/assets/9eea226f-5cf4-4f67-b4d8-347a00826245)

### Expected Behavior

(x) icon on the top right

### To Reproduce

1. Open assistant

**Comment by julien-nc** [comment]
Hey. I can't reproduce on NC 30.0.2 or stable30 or master with Assistant v2.1.1 or master.

Maybe the style is changed by something else in the page you're in. Does it happen when you open the assistant from any page in NC?

**Comment by ChristophWurst** [comment]
I can also no longer reproduce after a fresh page reload …

It must be something dynamic that triggers it. You can close the report for now and I'll see if this ever happens again
