### ISSUE TITLE
Conversational frontend

### ISSUE THREAD

**Issue by overcuriousity** [nextcloud/assistant#17]
### Describe the feature you'd like to request

I would like to have some kind of conversational frontend for actually chatting with the LLM. Maybe one wants to generate some text or code and be immediately able to make remarks and suggestions to refine the result, as this it what conversational AIs are typically used for.

### Describe the solution you'd like

I would like to have some frontend which can be compared to ChatGPT or GPT4all which can be operated via nextcloud assistant, utilizing the existing nextcloud/llm or localAI backends. It would be necessary to adjust the nextcloud assistant to have a larger context window for that to have an actual conversation. The functionality could even present a possibility to interact with other nextcloud apps, such as creating calendar entries, notes, reminders, tasks, deck cards, workflows (...) via natural language. I think this would separate nextcloud significantly from other similar products on the market.

### Describe alternatives you've considered

I used things like GPT4All or StableDiffusion on my local machine previously, but it would be nice to have that on nextcloud, as accessing these services remotely would involve quite some work, while nextcloud is already well thought through, secure and making it accessible via the net is trivial.

**Comment by marcelklehr** [comment]
Released as part of nextcloud 30 / Hub 9
