### ISSUE TITLE
Free prompt submit button confusing

### ISSUE THREAD

**Issue by szaimen** [nextcloud/assistant#2]
### Describe the feature you'd like to request

The free prompt submit button is confusing because it does not clearly state what it does.

See 
![image](https://github.com/nextcloud/assistant/assets/42591237/658f0a17-1a30-4180-bcc5-9f2b4a2ef267)

### Describe the solution you'd like

Adjust the button to state more clearly what it does, e.g. `Submit Free text`.

cc @nextcloud/designers 

### Describe alternatives you've considered

Nothing

**Comment by jancborchardt** [comment]
Yeah, "Submit free prompt" would be a bit better here. The other ones are already worded as commands so it works for button labels, while "Free prompt" is not.

**Comment by julien-nc** [comment]
@marcelklehr Would you be fine with changing https://github.com/nextcloud/server/blob/cf2e3bc0ee73afb2551ee7c763de3b1195953205/lib/public/TextProcessing/FreePromptTaskType.php#L56
to something that expresses an action like "Run free prompt" or "Submit free prompt" or "Submit free question"?

An alternative would be to add a `getActionName` method to `ITaskType` so task types have a distinct name and action name. IMO this is better and not so costly as very few task types are implemented.

**Comment by marcelklehr** [comment]
Task names are not guaranteed to be verbs. Why not change the submit button to something generic like "run"/"process"/"submit"?

**Comment by jancborchardt** [comment]
We now have the Chat with AI which does not use any label, and "Generate text" uses "Send request". So I would consider this resolved.

![Image](https://github.com/user-attachments/assets/9004ccf7-7568-4256-881b-3373a0620bb0)
