### ISSUE TITLE
Trigger button is not accessible

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/assistant#26]
Found while looking at other apps and having the assistant app enabled, reported by [axe](https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/)

<img width="2006" alt="Screenshot 2024-01-10 at 16 11 42" src="https://github.com/nextcloud/assistant/assets/3404133/c8190808-ecd6-4305-9854-a16d50f7a1f4">

**Comment by julien-nc** [comment]
Thanks :blue_heart: 
The title was on the parent div. It's now on the `<a>`. Is it enough?

**Comment by juliushaertl** [comment]
Yes, for the reported error that is fine. Having a look at the element it would probably be good to switch it to a button or at least https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

**Comment by julien-nc** [comment]
It's now similar to the unified search one.
https://github.com/nextcloud/assistant/commit/0968c6baa79633872004800a6f02567dfad198a1

**Comment by juliushaertl** [comment]
Looks good now :)
