### ISSUE TITLE
Adjust icon transparency

### ISSUE THREAD

**Issue by pschopen** [nextcloud/assistant#4]
### Which version of assistant are you using?

1.01

### Which version of Nextcloud are you using?

NC Hub 6

### Describe the Bug

All the icons on the right (search, people, etc.) have a half transparent icon. Why doesn't the assistant?

![grafik](https://github.com/nextcloud/assistant/assets/65334274/3895b42e-09d9-4b26-ad52-c18dad0d1c46)

### Expected Behavior

Half transparent icon

### To Reproduce

just install the app

**Comment by julien-nc** [comment]
Thank you for the issue. This has been fixed and will be included in the next release.
