### ISSUE TITLE
Option to disable image generation

### ISSUE THREAD

**Issue by mwinkens** [nextcloud/assistant#74]
### Which version of assistant are you using?

latest

### Which version of Nextcloud are you using?

28.0.4

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome, Firefox

### Describe the Bug

You can only disable image generation for the smart picker (on multiple places), but not for the `Assistant Processing Form`. I would really like to set it to NONE, but this button does nothing:

![bilderstellung](https://github.com/nextcloud/assistant/assets/104770531/ddd0f212-3c70-4012-93e7-d938ad9981ab)

### Expected Behavior

I expect, that it can be disabled

### To Reproduce

Try to disable it, you can only disable it for the smart picker (at multiple places)

**Comment by julien-nc** [comment]
These settings are implemented in Nextcloud's code (server). Nothing we can change in the Assistant.

But I agree with you it would be useful to be able to not select any provider for a feature. We are starting to refactor all the AI-related APIs. Your suggestion will be implemented along the way.
Let's keep this issue open in the meantime.

**Comment by mwinkens** [comment]
This seems to be fixed with the newest version of the OpenAI app with version 2.0.0. Thank you for your work, this is really appreciated 👍 @julien-nc
