### ISSUE TITLE
No results in choose a Task

### ISSUE THREAD

**Issue by chrsBlank** [nextcloud/assistant#9]
### Which version of assistant are you using?

1.0.1

### Which version of Nextcloud are you using?

 27.1.1

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

chromium, kubuntu

### Describe the Bug

When i click on the assistant button on the top right i get the pop up, i then try to pick a task but none is shown
![image](https://github.com/nextcloud/assistant/assets/36511746/0a002c3e-e9bf-4448-920e-9fd1027a0cb5)

### Expected Behavior

Get tasks to perform

### To Reproduce

install the app, click on the top right button

**Comment by chrsBlank** [comment]
This is from my "personal" settings
![image](https://github.com/nextcloud/assistant/assets/36511746/7dc5e85d-87db-484a-b4e0-9440b22f211c)

same deal in the Artificial Intelligence tab from the "administrator" settings

**Comment by graphius** [comment]
You must add an AI framework. I have been able to get [Local Large language model](https://apps.nextcloud.com/apps/llm) to work. 
I have not been able to get LocalAI to work and have not tried OpenAI.

**Comment by chrsBlank** [comment]
I will try that tomorrow. I knew something was off but could not put my finger on it. I saw a mention in the README but i had already posted it and havent tested it.

**Comment by chrsBlank** [comment]
Installed [Local Large language model](https://apps.nextcloud.com/apps/llm) and everything seems to work : ) 
Thank you @graphius
